Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 650, Center_X: 319, Center_Y: 250, Front: 270, Inner: 38, Outer: 228,
  X: 308, Y: 266}
FPS: 17
HSV:
  Ball: [0, 30, 30, 94, 30, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Green: [172, 202, 49, 86, 4, 63]
  White: [0, 359, 0, 22, 0, 23]
  Yellow: [32, 80, 32, 100, 0, 100]
  black: {angle: 3, gray: 26}
  white: {angle: 3, gray: 123}
Parameterbutton: 7
SCAN: {Angle_Near_Gap: 6, Angle_range_1: 3, Angle_range_2_3: 3, Dont_Search_Angle_1: 332,
  Dont_Search_Angle_2: 88, Dont_Search_Angle_3: 209, Magn_Far_End: 190, Magn_Far_Start: 141,
  Magn_Middle_Start: 90, Magn_Near_Gap: 4, Magn_Near_Start: 33}
blackItem: {angle: 3, gray: 40}
vision:
  FPS: 0
  SCAN: {Angle_Near_Gap: 4, Angle_range_1: 1, Angle_range_2_3: 1, Dont_Search_Angle_1: 0,
    Dont_Search_Angle_2: 0, Dont_Search_Angle_3: 0, Magn_Far_End: 1, Magn_Far_Start: 1,
    Magn_Near_Gap: 1, Magn_Near_Start: 1}
whiteline: {angle: 4, gray: 100}
