Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 654, Center_X: 320, Center_Y: 254, Front: 266, Horizon: 148,
  Inner: 52, Outer: 228, X: 308, Y: 266}
FPS: 17
HSV:
  Ball: [0, 54, 30, 100, 30, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Green: [120, 200, 52, 93, 40, 100]
  White: [0, 359, 0, 22, 0, 23]
  Yellow: [32, 80, 29, 100, 0, 100]
  black: {angle: 3, gray: 26}
  white: {angle: 3, gray: 203}
Parameterbutton: 7
SCAN: {Angle_Near_Gap: 4, Angle_range_1: 5, Angle_range_2_3: 2, Dont_Search_Angle_1: 332,
  Dont_Search_Angle_2: 91, Dont_Search_Angle_3: 206, Magn_Far_End: 228, Magn_Far_Start: 151,
  Magn_Middle_Start: 90, Magn_Near_Gap: 2, Magn_Near_Start: 33}
blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
