Attack_Strategy: [0]
Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 650, Center_X: 307, Center_Y: 248, Front: 270, Inner: 45, Outer: 284,
  X: 308, Y: 266}
Chase_Strategy: [0]
Corner_Kick: [1.2, 60, 90, 50]
Distance:
  Gap: 20
  Pixel: [0, 21, 46, 66, 82, 94, 102, 109, 115, 121, 125, 129]
  Space: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220]
Distance_Settings: [0, 0, 0]
Dorsad_Attack: [6, 90, 180, 2, 1, 2]
FPS: 17
General_PathPlan: [0.1, 0.1, 3, 0.1, 2, 0.2, 3, 1.5, 10, 3, 10, 3]
Goalkeeper: [1.5, 1.5, 1.5, 0]
HSV:
  Ball: [1, 24, 50, 93, 18, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Bluerange: [245, 204, 255, 179, 255, 72]
  Green: [172, 202, 49, 86, 4, 63]
  Greenrange: [188, 114, 255, 130, 255, 0]
  Redrange: [36, 0, 255, 118, 255, 0]
  White: [0, 359, 0, 22, 0, 23]
  Whiterange: [227, 146, 166, 13, 255, 134]
  Yellow: [82, 104, 32, 100, 0, 100]
  Yellowrange: [103, 59, 255, 70, 255, 137]
  black: {angle: 1, gray: 29}
  white: {angle: 1, gray: 170}
IsSimulator: 0
Parameterbutton: 4
Penalty_Kick: [-45, 2]
RobotNumber: 1
SCAN: {Angle_Near_Gap: 4, Angle_range_1: 3, Angle_range_2_3: 3, Dont_Search_Angle_1: 332,
  Dont_Search_Angle_2: 86, Dont_Search_Angle_3: 213, Magn_Far_End: 240, Magn_Far_Start: 141,
  Magn_Middle_Start: 90, Magn_Near_Gap: 4, Magn_Near_Start: 47}
SPlanning_Velocity: [1.5, 0.6, 100, 80, 40, 20, 144, 7]
SideSpeedUp: [0.73, 1.2, 0.7, 5, 17.6]
TypeS_Attack: [1.2, 0.2]
TypeU_Attack: [0.8, 1, -90, 90, 0.6, 0.3, 10, 20]
Zone_Attack: [0.85, 1.25]
blackItem: {angle: 3, gray: 40}
hold_condition: [3, 0.33, 9, 0.4]
vision:
  Camera: {Focal: 13.971313932573906, High: 650.0}
  Center: {Camera_high: 670, Center_X: 321, Center_Y: 253, Front: 188, Inner: 37,
    Outer: 223, X: 308, Y: 266}
  FPS: 20
  HSV:
    Ball: [0, 34, 27, 100, 28, 100]
    Blue: [170, 258, 64, 81, 36, 67]
    Green: [80, 170, 28, 87, 26, 84]
    White: [0, 360, 0, 27, 0, 31]
    Yellow: [30, 92, 28, 98, 24, 100]
    black: {angle: 20, gray: 20}
    white: {angle: 1, gray: 170}
  Parameterbutton: 4
  SCAN: {Angle_Near_Gap: 4, Angle_range_1: 2, Angle_range_2_3: 4, Dont_Search_Angle_1: 47,
    Dont_Search_Angle_2: 164, Dont_Search_Angle_3: 285, Magn_Far_End: 212, Magn_Far_Start: 141,
    Magn_Middle_Start: 93, Magn_Near_Gap: 4, Magn_Near_Start: 40}
  blackItem: {angle: 3, gray: 40}
  whiteline: {angle: 4, gray: 100}
whiteline: {angle: 4, gray: 100}
